# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

SUBDIRS += src 
TEMPLATE = subdirs 
CONFIG += debug \
          warn_on \
          qt \
          thread 
DEFINES = -D_DEBUG 
QMAKE_CXXFLAGS_DEBUG += -O0 
QMAKE_CXXFLAGS_RELEASE += -O2 
QMAKE_LFLAGS_DEBUG = -LOpenMesh_Core 
QMAKE_LFLAGS_RELEASE = -LOpenMesh_Core 
INCLUDEPATH = -I/client/include 
